package com.bytheproject.flashforge.ui.theme


import androidx.compose.ui.graphics.Color

val Seed = Color(0xFFFF0083)

val PrimaryLight = Color(0xFFBA005E)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFFFD9E1)
val OnPrimaryContainerLight = Color(0xFF8E0046)
val SecondaryLight = Color(0xFF80543C)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFFFDBCA)
val OnSecondaryContainerLight = Color(0xFF653D27)
val TertiaryLight = Color(0xFF58642A)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFDBEAA1)
val OnTertiaryContainerLight = Color(0xFF404B14)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF93000A)
val BackgroundLight = Color(0xFFFFF8F7)
val OnBackgroundLight = Color(0xFF251819)
val SurfaceLight = Color(0xFFFFF8F7)
val OnSurfaceLight = Color(0xFF251819)
val SurfaceVariantLight = Color(0xFFFCDBDA)
val OnSurfaceVariantLight = Color(0xFF584141)
val OutlineLight = Color(0xFF8B7171)
val OutlineVariantLight = Color(0xFFDFBFBF)
val ScrimLight = Color(0xFF000000)
val InverseSurfaceLight = Color(0xFF3B2D2D)
val InverseOnSurfaceLight = Color(0xFFFFEDEC)
val InversePrimaryLight = Color(0xFFFFB1C6)
val SurfaceDimLight = Color(0xFFEBD5D4)
val SurfaceBrightLight = Color(0xFFFFF8F7)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFFFF0F0)
val SurfaceContainerLight = Color(0xFFFFE9E8)
val SurfaceContainerHighLight = Color(0xFFFAE3E2)
val SurfaceContainerHighestLight = Color(0xFFF4DDDD)

val PrimaryDark = Color(0xFFFFB1C6)
val OnPrimaryDark = Color(0xFF650030)
val PrimaryContainerDark = Color(0xFF8E0046)
val OnPrimaryContainerDark = Color(0xFFFFD9E1)
val SecondaryDark = Color(0xFFF3BA9D)
val OnSecondaryDark = Color(0xFF4A2713)
val SecondaryContainerDark = Color(0xFF653D27)
val OnSecondaryContainerDark = Color(0xFFFFDBCA)
val TertiaryDark = Color(0xFFBFCD88)
val OnTertiaryDark = Color(0xFF2A3400)
val TertiaryContainerDark = Color(0xFF404B14)
val OnTertiaryContainerDark = Color(0xFFDBEAA1)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF1C1011)
val OnBackgroundDark = Color(0xFFF4DDDD)
val SurfaceDark = Color(0xFF1C1011)
val OnSurfaceDark = Color(0xFFF4DDDD)
val SurfaceVariantDark = Color(0xFF584141)
val OnSurfaceVariantDark = Color(0xFFDFBFBF)
val OutlineDark = Color(0xFFA68A8A)
val OutlineVariantDark = Color(0xFF584141)
val ScrimDark = Color(0xFF000000)
val InverseSurfaceDark = Color(0xFFF4DDDD)
val InverseOnSurfaceDark = Color(0xFF3B2D2D)
val InversePrimaryDark = Color(0xFFBA005E)
val SurfaceDimDark = Color(0xFF1C1011)
val SurfaceBrightDark = Color(0xFF443636)
val SurfaceContainerLowestDark = Color(0xFF160B0C)
val SurfaceContainerLowDark = Color(0xFF251819)
val SurfaceContainerDark = Color(0xFF291C1D)
val SurfaceContainerHighDark = Color(0xFF342727)
val SurfaceContainerHighestDark = Color(0xFF3F3131)